"""
Django settings for study project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(4bzqk5_b)j3n#p8k6j15qh+odo^)qzdva7s2d(qq#f071cd-r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['virlea.herokuapp.com', '127.0.0.1', 'stuclan.com', 'www.stuclan.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'rest_auth.registration',
    'allauth.socialaccount',
    'storages',
    'corsheaders',
    "taggit",
    
    #my api
    'Myapi',
    'phone_field',
    'django_filters',
    # "djangorave", 
    'ravepay',
    'rating',
    'star_ratings',
]
 
MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.BrokenLinkEmailsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
] 

RAVE_PRODUCTION_PUBLIC_KEY = "FLWPUBK-bcf023d60ead2cc5901fff8dddef812d-X"
RAVE_PRODUCTION_SECRET_KEY = "FLWSECK-f5cefec0505eb5a8a14970aa37d49a2a-X"
RAVE_SANDBOX_PUBLIC_KEY = "FLWPUBK_TEST-f56a181128b8edde1c201c84114c75a5-X"
RAVE_SANDBOX_SECRET_KEY = "FLWSECK_TEST-aa528235ea8465216753394deccb2beb-X"
RAVE_SANDBOX = True

ROOT_URLCONF = 'study.urls'

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    # ]
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 2,
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'templates', 'allauth')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'study.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


 
# DATABASES = {
# 'default': {
# 'ENGINE': 'django.db.backends.mysql',
# 'NAME': 'virlea1',
# 'USER': 'admin',
# 'PASSWORD': 'treasure12',
# 'HOST': 'database-1.cbsagvho1jgh.eu-west-3.rds.amazonaws.com',
# 'PORT': '3306',
# 'OPTIONS': {
# 'init_command': "SET sql_mode = 'STRICT_TRANS_TABLES'"
# }
# }
# }

DATABASES = {
'default': {
'ENGINE': 'django.db.backends.mysql',
'NAME': 'stuclan',
'USER': 'admin',
'PASSWORD': 'treasure12',
'HOST': 'legit.clvamfqpft4e.us-east-2.rds.amazonaws.com',
'PORT': '3306',
'OPTIONS': {
'init_command': "SET sql_mode = 'STRICT_TRANS_TABLES'"
}
}
} 
# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ORIGIN_ALLOW_ALL = True
# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

RAVEPAY_WEBHOOK_HASH="DJANGO_RAVEPAY"


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')





# STATICFILES_DIRS = (
#     ("js", os.path.join(STATIC_ROOT, 'js')),
#     ("css", os.path.join(STATIC_ROOT, 'css')),
#     ("images", os.path.join(STATIC_ROOT, 'images')),
#     ("fonts", os.path.join(STATIC_ROOT, 'fonts')),
# )
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'


EMAIL_HOST_USER = 'virlearners@gmail.com'
EMAIL_HOST_PASSWORD = 'rfuphzgqhtcneszd'
EMAIL_USE_TLS = True
MAIL_USE_SSL = False
EMAIL_PORT = 587

SITE_ID = 1

LOGIN_URL = '/Virlearners-confirm/'
LOGIN_REDIRECT_URL = '/Virlearners-confirm/'
REST_AUTH_REGISTER_SERIALIZERS = {
        'REGISTER_SERIALIZER': 'Myapi.serializers.RegisterSerializer',
}
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True   
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
REST_SESSION_LOGIN = True


AUTHENTICATION_BACKENDS = (
 # Needed to login by username in Django admin, regardless of `allauth`
 "django.contrib.auth.backends.ModelBackend",

 # `allauth` specific authentication methods, such as login by e-mail
 "allauth.account.auth_backends.AuthenticationBackend",
)



USE_S3 = True
if USE_S3:
    AWS_ACCESS_KEY_ID = 'AKIA47UAIC2MF6XFTC5I'
    AWS_SECRET_ACCESS_KEY = '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'
    AWS_STORAGE_BUCKET_NAME = 'legiter'
    # AWS_LOCATION = 'static'
    AWS_S3_SECURE_URLS = False
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    # STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    # STATIC_LOCATION = 'static'
    # STATICFILES_STORAGE = 'web.storage_backends.StaticStorage'
    AWS_S3_CUSTOM_DOMAIN='%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
    # STATICFILES_DIRS = [
    #     os.path.join(BASE_DIR, 'static'),
    # ] 
     
    # STATIC_ROOT = os.path.join(BASE_DIR, 'http://%s.s3.amazonaws.com//static/'  % AWS_STORAGE_BUCKET_NAME)
    # STATIC_URL='https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)
    # ADMIN_MEDIA_PREFIX = STATIC_URL + 'admin/'
    # STATICFILES_FINDERS = (           'django.contrib.staticfiles.finders.FileSystemFinder',    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # )

    S3_URL = 'https://%s.s3.amazonaws.com/' % AWS_STORAGE_BUCKET_NAME  
    PUBLIC_MEDIA_LOCATION = 'media'
    MEDIA_URL = f'{S3_URL}/{PUBLIC_MEDIA_LOCATION}/'
    MEDIA_ROOT = 'https://%s.s3.amazonaws.com/media/'  % AWS_STORAGE_BUCKET_NAME 
    DEFAULT_FILE_STORAGE = 'study.storage_backends.PublicMediaStorage'
    