# Generated by Django 3.0.5 on 2020-05-14 21:52

import Myapi.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(blank=True, max_length=100)),
                ('Course_Language', models.CharField(max_length=100)),
                ('Course_duration', models.DurationField(default=datetime.timedelta(days=3))),
                ('course_status', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Myapi.models.user_directory_path)),
                ('file_type', models.CharField(max_length=100)),
            ],
        ),
    ]
