# Generated by Django 3.0.5 on 2020-05-15 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0003_auto_20200515_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section_material',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_material', to='Myapi.Course_content'),
        ),
    ]
