# Generated by Django 3.0.5 on 2020-05-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0004_auto_20200515_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section_material',
            name='file_name',
            field=models.CharField(max_length=300),
        ),
    ]
