# Generated by Django 3.0.5 on 2020-05-22 10:39

import Myapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0005_auto_20200518_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section_material',
            name='file',
            field=models.FileField(upload_to=Myapi.models.user_directory_path),
        ),
    ]
