# Generated by Django 3.0.5 on 2020-05-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0006_auto_20200522_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='About_course',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='course',
            name='Course_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
