# Generated by Django 3.0.5 on 2020-05-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0007_auto_20200523_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_category_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
