# Generated by Django 3.0.5 on 2020-05-23 18:17

import Myapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0008_course_course_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='file',
            field=models.FileField(default=1, upload_to=Myapi.models.user_directory_path1),
            preserve_default=False,
        ),
    ]
