# Generated by Django 3.0.5 on 2020-06-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0011_course_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
