# Generated by Django 3.0.5 on 2020-06-11 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Myapi', '0021_auto_20200611_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='institution',
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ManyToManyField(blank=True, related_name='institution', to=settings.AUTH_USER_MODEL),
        ),
    ]
