# Generated by Django 3.0.5 on 2020-06-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0022_auto_20200611_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instructor',
            field=models.BooleanField(default='False'),
        ),
    ]
