# Generated by Django 3.0.5 on 2020-06-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0023_auto_20200616_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=35)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='Course_category',
        ),
        migrations.AddField(
            model_name='course',
            name='Course_category',
            field=models.ManyToManyField(blank=True, to='Myapi.Category'),
        ),
    ]
