# Generated by Django 3.0.5 on 2020-06-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0024_auto_20200616_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to='Myapi.Course')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='The_profile', to='Myapi.profile')),
            ],
        ),
    ]
