# Generated by Django 3.0.5 on 2020-06-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0025_course_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_progress',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='Myapi.course_progress'),
        ),
    ]
