# Generated by Django 3.0.5 on 2020-06-18 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0026_auto_20200618_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='courses',
        ),
        migrations.AddField(
            model_name='course_progress',
            name='content',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='the_profile', to='Myapi.profile'),
            preserve_default=False,
        ),
    ]
