# Generated by Django 3.0.5 on 2020-06-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0027_auto_20200618_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_progress',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Myapi.profile'),
        ),
    ]
