# Generated by Django 3.0.5 on 2020-06-18 11:59

import Myapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0028_auto_20200618_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course_progress',
            name='steps',
            field=models.IntegerField(default=0),
        ),
    ]
