# Generated by Django 3.0.5 on 2020-06-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0029_auto_20200618_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_progress',
            name='steps',
            field=models.IntegerField(default=0),
        ),
    ]
