# Generated by Django 3.0.5 on 2020-06-18 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Myapi', '0030_auto_20200618_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fr_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fr_content_type', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
