# Generated by Django 3.0.5 on 2020-06-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0031_course_fr_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fr_content_type',
        ),
    ]
