# Generated by Django 2.2.10 on 2020-07-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0034_course_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('data', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.ManyToManyField(blank=True, related_name='certificate', to='Myapi.Certificate'),
        ),
    ]
