# Generated by Django 2.2.10 on 2020-07-14 18:04

import Myapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0038_auto_20200713_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to=Myapi.models.user_directory_path2),
        ),
    ]
