# Generated by Django 2.2.10 on 2020-07-15 20:24

import Myapi.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0039_certificate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to=Myapi.models.user_directory_path3),
        ),
        migrations.CreateModel(
            name='Certificatess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('data', models.CharField(blank=True, max_length=100)),
                ('contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certi_courses', to='Myapi.profile')),
            ],
        ),
    ]
