# Generated by Django 2.2.10 on 2020-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0040_auto_20200715_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_progress',
            name='Last_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course_progress',
            name='completed_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
