# Generated by Django 2.2.10 on 2020-07-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0041_auto_20200717_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_progress',
            name='completed_time',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
