# Generated by Django 2.2.10 on 2020-07-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0042_auto_20200720_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_progress',
            name='Last_time',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
