# Generated by Django 2.2.10 on 2020-07-23 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Myapi', '0043_auto_20200720_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default='False')),
                ('ref_num', models.CharField(blank=True, max_length=2000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ManyToManyField(blank=True, related_name='all_course', to='Myapi.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
