# Generated by Django 2.2.10 on 2020-07-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0044_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
