# Generated by Django 2.2.10 on 2020-08-01 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0045_payments_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments_verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('txt_ref', models.CharField(blank=True, max_length=2000)),
                ('flw_ref', models.CharField(blank=True, max_length=2000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('muuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_user', to='Myapi.profile')),
                ('pd_course', models.ManyToManyField(blank=True, related_name='pd_course', to='Myapi.Course')),
            ],
        ),
    ]
