# Generated by Django 2.2.10 on 2020-08-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0046_payments_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments_verify',
            name='muuser',
        ),
        migrations.RemoveField(
            model_name='payments_verify',
            name='pd_course',
        ),
    ]
