# Generated by Django 2.2.10 on 2020-08-08 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Myapi', '0047_auto_20200803_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_course_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=2000)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('duration', models.CharField(blank=True, max_length=1000)),
                ('section_number', models.CharField(blank=True, max_length=1000)),
                ('extra', models.CharField(blank=True, max_length=1000)),
                ('read', models.BooleanField(default='False')),
                ('approved', models.BooleanField(default='False')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
