# Generated by Django 2.2.10 on 2020-09-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0051_auto_20200914_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
