# Generated by Django 2.2.13 on 2022-02-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0052_feedback_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='About_course',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
